### ISSUE TITLE
item.icons not set

### ISSUE THREAD

**Issue by Yousei9** [kirazy/reskins-bobs#2]
Please set item.icons and entity.icons in data-updates, so I can create correct icons in LEP+ from yours.

**Comment by kirazy** [comment]
Fixed with kirazy/reskins-library@e1925a687d158fe9ebafbf5397e31ad9a159ad55. :)

**Comment by kirazy** [comment]
When I have more of Bobs supported I'll stop trying to play nice with ShinyBobGFX, at which point most everything will be done in data.lua. I look forward to that day...
