### ISSUE TITLE
Mod Incompatibility - Picker Tweaks & Picker Pipe Tools

### ISSUE THREAD

**Issue by Goatle** [kirazy/reskins-bobs#3]
Hi Kirazy,

Thanks for the great mod! Loving it. 

I ran into an issue with the mod and two of the Picker series mods, namely [Picker Tweaks](https://mods.factorio.com/mod/PickerTweaks) and [Picker Pipe Tools](https://mods.factorio.com/mod/PickerPipeTools).

Using Reskin Bobs and these mods I get the following error on startup.

https://pastebin.com/mE79BXCJ

After disabling Picker Tweaks, Picker Pipe Tools then errors out with the following.

`97.780 Error ModManager.cpp:1514: Error while loading entity prototype "pipe-clamped-single" (pipe-to-ground): Key "icon" not found in property tree at ROOT.pipe-to-ground.pipe-clamped-single.icons[0]
Modifications: Picker Pipe Tools`

The game then loads with these disabled. If I disable Reskin Bobs these errors do not occur.

I do have a load of additional mods, and can provide them if you need.

Additional Info: 

Factorio Version 0.18.34

**Comment by kirazy** [comment]
I'd wager this is related to me setting `icon = nil` when I set the `icons` field. Then Picker Tweaks / Picker Pipe Tools comes along and expects `icon`, has no method to account for `icons`, and throws a startup error. This is a Picker Tweaks issue, `icons` supersedes `icon` when it is defined (so Picker Tweaks shouldn't be pulling from `icon` in the first place in this circumstance) so even if I were to not nil out the `icon` field, the issue remains that Picker Tweaks is pulling an inactive icon definition.

The specific case here is that Picker Tweaks is trying to modify the nuclear reactor (or even just fetch the icon?) and I have modified the nuclear reactor in `data-updates.lua`.

**Comment by Goatle** [comment]
Thank you for the super fast response and cross posting it over to Nexela's github.

Nice to know some of the specifics as to why this is not working.

**Comment by kirazy** [comment]
Both issues are the same, really. I nil out `icon` and Picker Tweaks and Picker Pipe Tools don't handle that properly.

**Comment by kirazy** [comment]
This is now fixed.

**Comment by kirazy** [comment]
Rather, the issue with Picker Tweaks is fixed. I'm checking the issue with Picker Pipe Tools now...

**Comment by kirazy** [comment]
There, now this is fixed. :)
