### ISSUE TITLE
Warptorio2 cross-post from Factorio mod website

### ISSUE THREAD

**Issue by Speedyquader** [kirazy/reskins-bobs#33]
Here's the pic of the error screen: https://imgur.com/c5gnQ86

Here's what MFerrari, the mod author of Warptorio2 Expansion, had to say about the issue: "Report to the reskins mod author. He should test both "icon" and "icons". I only use "icons" on some prototypes, and "icon" is nil in this case."

Thanks!

**Comment by kirazy** [comment]
I've discussed it with MFerrari and he's going to implement one of the fixes I suggested, which should resolve the issue when he gets around to doing so. Won't need to bandaid it. :D
