### ISSUE TITLE
Bob's Modules intermediates Reskins

### ISSUE THREAD

**Issue by mxcop** [kirazy/reskins-bobs#44]
Hey there 👋 

I've been making some reskins for the module intermediate parts.
I was hoping I'd be able to contribute them to this repo 😄 

*Some of the sprites*
![image](https://github.com/kirazy/reskins-bobs/assets/44031065/82019b62-be68-4fdf-8a24-298f4bc66c16)

So if you like them, or you have any feedback, let me know.

*PS. I'm not an artist*

**Comment by mxcop** [comment]
*All the sprites*
![image](https://github.com/kirazy/reskins-bobs/assets/44031065/4becfab6-636b-4de7-8987-728f94eb42fb)

The module contacts and casing could be a lot better, but I'm not that good at art.
So if you'd want to improve them, feel free to do so :D

**Comment by kirazy** [comment]
...!

Not an artist... I dunno. Concept wise these are amazing. I stalled on these a long time ago 'cause it's hard to be consistent with vanilla circuit design and also pack in all the necessary details. Imo these are sufficiently similar to match the style but really good.

The only thing that would need work really are that there are no differences beyond color for same-tier items which is not ideal for color blind support.

I'd love to improve these if you're willing to share the source files. Credit is all _absolutely_ yours.

**Comment by kirazy** [comment]
lol though it's not like the _modules_ are different, really, aside from color...

**Comment by mxcop** [comment]
Haha yea true, I do agree some graphical differences would be sick.
However it does seem like a large undertaking to do that for each module :p
<sub>(I also think the `Module Contact` sprite leaves a lot to be desired)</sub>

<br>

I wanted to make a PR to this repo with the new sprites, however I don't fully understand the project structure or the library.
So maybe you could help me with that?

The images are all located in this repo : [https://github.com/mxcop/maxi-reskins](https://github.com/mxcop/maxi-reskins)
