### ISSUE TITLE
AAI Loader / Bob's Logistics

### ISSUE THREAD

**Issue by KiwiHawk** [kirazy/reskins-bobs#45]
Support for AAI Loaders is being added in Bob's Logistics 1.2.0

It would be great if these could get the tier indicators!

![image](https://github.com/kirazy/reskins-bobs/assets/59639/1cb8fd35-17d8-43ed-9ade-ef8aa737b22d)

https://github.com/modded-factorio/bobsmods/issues/109

**Comment by kirazy** [comment]
Just noting for the record that there's an existing mod, https://mods.factorio.com/mod/aai-loaders-bobs, that bridges AAI Loaders, Bob's, and Artisanal Reskins.

May need to mark incompatible once implemented.

**Comment by KiwiHawk** [comment]
Yes, I saw that. It deletes existing loaders and recreates them. So the changes released in the latest version of Bob's Logistics mod have no effect on that mod.

**Comment by kirazy** [comment]
Implemented in https://github.com/kirazy/reskins-compatibility/commit/72ba7e45eb9cb689477c2f08221e7b7c8f0248e0
