### ISSUE TITLE
Non-recoverable error on Startup on 0.0.16

### ISSUE THREAD

**Issue by fkuhnert** [kirazy/reskins-bobs#5]
![image](https://user-images.githubusercontent.com/29618514/87973238-92842a00-ca9e-11ea-87df-395c3f921144.png)

This happens on startup.

I have "name" progression enabled. I was on 0.0.14 before

**Comment by kirazy** [comment]
...what is your game version?

**Comment by fkuhnert** [comment]
That's it! I'm on 0.18.35 because 0.18.36 wasn't working on an earlier version. My bad.

**Comment by kirazy** [comment]
Also my bad for not incrementing the minimum game version. I'm also going to improve how this process works to fail quietly instead of throwing a startup error, so thanks. :D
