### ISSUE TITLE
Inserter texture miscoordinate on low-res graphics

### ISSUE THREAD

**Issue by Kvazikvark** [kirazy/reskins-bobs#7]
Good day!
When yellow inserters pick up anything texture of hand flies in air near him. Did not check with any other inserters except burning (all is ok with him).
This happen only on low-res texture graphics and with every version of mod from 0.0.22 to last. Use with bob's inserters mod (1.0.1).

![1](https://user-images.githubusercontent.com/14229931/96098026-55330b00-0eda-11eb-9808-dff90b144d3d.jpg)
![2](https://user-images.githubusercontent.com/14229931/96098000-4e0bfd00-0eda-11eb-94da-25029210a806.png)

**Comment by kirazy** [comment]
That is bizarre. The bug only happens for hand-closed, not hand-open, but the graphics are specified by the exact same code, the only difference is that the closed-state uses the string "closed" instead of "open" in the file reference, and the files themselves are properly positioned. I'm investigating.

**Comment by kirazy** [comment]
This may be a Factorio bug:
![73496270](https://user-images.githubusercontent.com/35714562/96101618-808e0980-0e8a-11eb-8651-642b61c33d42.png)

Every single hand picture is defined using the exact same function, just pointing to different images. I'm remaking the images on the off chance something is wrong with the png file.

**Comment by Kvazikvark** [comment]
Yep, I've tried to investigate himself, but can't find any error in mod code. Also came to the conclusion that this may be the problem of the Factory itself and finaly report here.

**Comment by kirazy** [comment]
Ah, nope, found it. I was looking at the inserter-closed-mask file, when I needed to be looking at the long-handed-inserter-closed-mask file. It was not properly rescaled.

**Comment by kirazy** [comment]
I will fix this as part of the regular update cycle, but if you would like to fix it in your game now you can download the corrected image and replace your local copy.

**Comment by Kvazikvark** [comment]
Yep, thank you very much!

**Comment by Kvazikvark** [comment]
All is super now! Thank you again!
