### ISSUE TITLE
Mipmaps warning in log

### ISSUE THREAD

**Issue by flexoo** [kirazy/reskins-bobs#8]
Found a warning in my log and thought I let you know.

54.335 Warning! Sprite at {0,0; 64x64} from __reskins-bobs__/graphics/icons/logistics/filter-inserter/filter-inserter-icon-highlights.png is defined with 4 mipmap levels, but level 1 is expected to be at {64,0; 32x32} which is out of bounds of the source image.

**Comment by kirazy** [comment]
Thanks for the report. Commit e3f3b08aacd8fe613e57e2a354161cccb8b132d8 fixes this.
